### ISSUE TITLE
Create a login webpage

### ISSUE THREAD

**Issue by andarilhoz** [fabiomaciel/simple-mtg#43]
Create the frontpage to authenticate users

**Comment by chainedcoder** [comment]
I sure can do this

**Comment by andarilhoz** [comment]
@stevenkayter  please, use this image as reference 

https://www.dropbox.com/s/89qbu3ompxec0vg/simple-magic-pb.png?dl=0

**Comment by andarilhoz** [comment]
@stevenkayter  thanks, that PR looks great (:
