### ISSUE TITLE
Create the sign up page front-end

### ISSUE THREAD

**Issue by andarilhoz** [fabiomaciel/simple-mtg#51]
The projects need's a sign up page following this model (but in english language):

https://www.dropbox.com/s/ikfaeenj61eya8h/Modelo-de-tela.png?dl=0

the labels are:

Name:
Username:
E-mail:
Confirm E-mail:
Password:
Confirm Password:

**Comment by hkveeranki** [comment]
I would like to work on this.

**Comment by andarilhoz** [comment]
@harry-7  cool, don't forget to keep it in a different branch (:

**Comment by hkveeranki** [comment]
@andarilhoz . what all I need to do ? Can you provide me with a check list with what all I have to do ? Also can I use more node modules like crypto and jsonwebtoken

**Comment by andarilhoz** [comment]
@harry-7 this issue is actually just for the html and css, but, if you want to make something in js, or even in the node part would be better to do it on this issue #42  (:

**Comment by hkveeranki** [comment]
@andarilhoz great. I would like to solve that one as well .. Can I solve both of them in a single shot ? Or do you want me to create two seperate pull requests ?

**Comment by andarilhoz** [comment]
@harry-7 two pr would be better (:

**Comment by hkveeranki** [comment]
@andarilhoz I created a new pull request with only the view .. Please see if it is okay and suggest any changes.

**Comment by andarilhoz** [comment]
Nice PR @harry-7 , already merged, i'll close this issue, about that another pr, that will be set on issue #42 please (:
